# Generated by Django 6.1.1 on 2026-10-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created_at"]},
        ),
    ]
